http {
    include mime.types;
    sendfile on;

    server {
        listen 80;
        listen [::]:80;

        autoindex on;

        server_name _;
        server_tokens off;

        root /app/static;
        gzip_static on;
    }
}
